### ISSUE TITLE
Error - Create a new table into sqlite database

### ISSUE THREAD

**Issue by Heryx** [jbogdani/BraDypUS#2]
Good morning.

I created a sqlite database following the guide. First I started by validating the database and it me returns only an error message **"Backup is not available: Executable sqlite3 was not found"**, maybe I have to install some sqlite features.

Then I tried to create a new table, but I get an error message: **"Errore. Non è stato possibile aggiornare i dati di configurazione"**

error.logs doesn't return any messages.

Thank you

**Comment by jbogdani** [comment]
As for the first question, bdus4 uses [db-dumber](https://github.com/spatie/db-dumper) library to perform backups. This means that bdus4 (as db-dumber) relies on `mysqldump`, `pg_dump` and `sqlite3` executables that must be available in the system. Please verify thet sqlite3 is installed on the server (by runnining `which sqlite3`) and install it if not (`sudo apt-get install sqlite3` on Debian based distros).

The second error probably depends on the missing library, as well.

ddus4 system dependencies are listed here: https://docs.bdus.cloud/environment/system-requirements
