### ISSUE TITLE
How to disable "Create new application" button

### ISSUE THREAD

**Issue by Heryx** [jbogdani/BraDypUS#6]
Hi everyone,

the [Creating a new application](https://docs.bdus.cloud/create_app/) page specifies how to disable the **Create new application** button, which is already active by default. But it is not clear that the file does not phisically exist, and in order to deactivate it, it must be created with any extension i.e. **UNSAFE_permit_app_creation.txt**

Greetings,
Giuseppe

**Comment by jbogdani** [comment]
Hello,
thank you for your posting, but this is not an issue related to the software itself but to the documentation and as such it should be posted to the [docs repository](https://github.com/lab-archeologia-digitale/docs).
Nevertheless, **pay attentions** to the docs that clearly state that the filename **must not** provide an extension:
![immagine](https://user-images.githubusercontent.com/1449293/173612515-b38a4c29-7552-40d3-b442-6aa0452b9a93.png)

Following the text in the image above, the `Create new application` button is not available on running installations that have **at least one application defined**.

It means that the button will appear: 
- if it is a new installation and no application has been defined yet, and
- if a file named exactly `UNSAFE_permit_app_creation` **with no extension** is available in the root of the installation.
